name: Prettier Lint

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Prettier Lint
    runs-on: ubuntu-latest
    steps:
      # v5 (at the time of commit)
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - name: Run prettier
        run: npx prettier --check .
